development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: premium_points
  username: "postgres"
  password: "postgres"
  pool:     5
  template: template0

test: &test
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: premium_points_test
  username: "postgres"
  password: "postgres"
  pool:     5
  template: template0